Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,32 @@
-name: "Next.js CD"
+# ---------------- Developed by Yousuf Kalim - Next.js CD ---------------- #
+# This workflow is a Continuous Integration/Continuous Deployment (CI/CD) pipeline for deploying a Next.js application
+# to a remote Ubuntu server.
+#
+# Here are some comments to make it easier for everyone to use:
+#
+# 1. The workflow uses environment variables to set the application name, component name, and release path.
+#    Ensure that these are set correctly according to your application's configuration.
+#
+# 2. The workflow runs on a push to the main branch and can be manually triggered with inputs to specify the target environment.
+#
+# 3. It's important to note that this workflow uses repository environment and several secrets and variables that need to be set up
+#    in order for it to work properly. You will need to create the following secrets in your repository environment:
+#
+#    3.1. [Env]_SERVER: the IP address or domain name of the remote server you are deploying to.
+#    3.2. [Env]_USER: the username you use to SSH into the remote server (root user is recommended).
+#    3.3. [Env]_KEY: the SSH private key you use to authenticate with the remote server.
+#    3.4. [Env]_NGINX: the contents of your NGINX configuration file. This should be a multi-line string with each line
+#         separated by a newline character.
+#
+# In addition, you will need to set up the following variables in your repository environment:
+#
+#    3.5. APP_NAME: the name of the project without spaces.
+#    3.6. COMPONENT_NAME: the name of the app component e.g: frontend, admin, backend.
+#
+# Overall, this workflow provides a good starting point for deploying a Next.js application to a remote server using GitHub Actions.
+# However, it should be customized according to your application's specific requirements.
+
+name: 'Next.js CD'
 
 env:
   APP_NAME: ${{ vars.APP_NAME }}
@@ -13,31 +41,35 @@ on:
   workflow_dispatch:
     inputs:
       environment:
-        description: "Target environment (dev)"
+        description: 'Target environment (dev, prod)'
         type: choice
         options:
           - dev
+          - prod
         required: true
 
 jobs:
   deploy:
-    runs-on: self-hosted
-    if: ${{ contains('["haazaa"]', github.actor) || github.event_name == 'push' || github.event.inputs.environment == 'dev' }}
+    runs-on: ubuntu-latest
 
     steps:
+      # Step 1: Checkout the code from the repository.
       - name: Checkout code
         uses: actions/checkout@v2
 
+      # Step 2: Setup Node.js with version 18.
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
           node-version: 18
 
+      # Step 3: Install dependencies and build the Next.js project.
       - name: Install deps and build project
         run: |
           yarn install
-          yarn build
+          CI= yarn run build
 
+      # Step 4: Transfer the built files to the remote server.
       - name: Transfer files to server
         uses: appleboy/scp-action@master
         with:
@@ -48,17 +80,30 @@ jobs:
           source: ".next,public,package.json,yarn.lock"
           target: ${{ env.RELEASE_PATH }}
 
-      - name: Deploy and restart
+      # Step 5: Deploy the application and restart services.
+      - name: Deploy and restart services
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets[format('{0}_SERVER', env.NODE_ENV)] }}
           username: ${{ secrets[format('{0}_USER', env.NODE_ENV)] }}
           key: ${{ secrets[format('{0}_KEY', env.NODE_ENV)] }}
           script: |
+            set -e  # Exit immediately if a command exits with a non-zero status.
+
+            # Change to the release directory
             cd ${{ env.RELEASE_PATH }}
+
+            # Install production dependencies
             yarn install --production
-            echo '${{ secrets[format('{0}_NGINX', env.NODE_ENV)] }}' > ${{ env.RELEASE_PATH }}/nginx.conf
-            sudo cp ${{ env.RELEASE_PATH }}/nginx.conf /etc/nginx/sites-available/${{ env.APP_NAME }}-${{ env.COMPONENT_NAME }}
-            sudo ln -sf /etc/nginx/sites-available/${{ env.APP_NAME }}-${{ env.COMPONENT_NAME }} /etc/nginx/sites-enabled/
-            sudo systemctl restart nginx
-            pm2 restart ${{ env.APP_NAME }}-${{ env.COMPONENT_NAME }} || pm2 start yarn --name "${{ env.APP_NAME }}-${{ env.COMPONENT_NAME }}" -- start
+
+            # Copy the Nginx configuration directly from the repository environment variable
+            echo '${{ secrets[format('{0}_NGINX', env.NODE_ENV)] }}' > ${{ env.RELEASE_PATH }}/.next/nginx.conf || exit 1
+
+            # Check Nginx configuration syntax
+            sudo nginx -t || exit 1
+            
+             # Restart Nginx service
+            sudo systemctl restart nginx || exit 1
+            
+            # Restart the PM2 application
+            pm2 restart ${{ env.APP_NAME }}-${{ env.NODE_ENV }} || pm2 start yarn --name "${{ env.APP_NAME }}-${{ env.NODE_ENV }}" -- start
